### ISSUE TITLE
Crash on Hypixel queue

### ISSUE THREAD

**Issue by mpfaff** [cominixo/BetterF3#10]
The following crash occurs consistently when enabling the debug hud on Hypixel's queue.

```
[11:45:05] [main/FATAL] (Not Enough Crashes In Game Crashes) Unreported exception thrown!
 java.lang.NullPointerException: Cannot invoke "Object.toString()" because "string" is null
	at me.cominixo.betterf3.utils.Utils.getStyledText(Utils.java:66) ~[59f44217-3fa2-48d5-9e05-2839c10b8673.jar:?]
	at me.cominixo.betterf3.modules.ServerModule.update(ServerModule.java:63) ~[59f44217-3fa2-48d5-9e05-2839c10b8673.jar:?]
	at net.minecraft.client.gui.hud.DebugHud.getNewLeftText(DebugHud.java:2149) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.gui.hud.DebugHud.handler$zoj001$renderLeftText(DebugHud.java:2230) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.gui.hud.DebugHud.renderLeftText(DebugHud.java) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.gui.hud.DebugHud.render(DebugHud.java:104) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:235) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:470) ~[minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1007) [minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:624) [minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:187) [minecraft-1.16.4-projectmapped-net.fabricmc.yarn-1.16.4+build.7-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8@net.fabricmc.yarn.1_16_4.1.16.4+build.7-v2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

**Comment by cominixo** [comment]
Should be fixed in https://github.com/cominixo/BetterF3/commit/821f1d78eb388d2d72d84f0d0f305afc90984363, will upload a release soon but for now it should be available in GIthub Actions
