### ISSUE TITLE
[Bug]: Game Crash when editing the f3 menu (modules)

### ISSUE THREAD

**Issue by TimmiPlayz** [cominixo/BetterF3#123]
### Describe the Bug

My Game crashes when I press "edit modules" . Here are my mods. Can anyone help me?

![Screenshot 2022-11-13 142557](https://user-images.githubusercontent.com/118113898/201524059-02eb522f-b3f3-4f4f-919d-564e543b2e15.png)

### Steps to Reproduce

Editing a module in the configuration menu 

### Expected Behavior

Game crashes

### Modloader Type

Fabric

### Modloader Version

fabric-loader-0.14.10-1.19.2

### Mod Version

4.0.0 Fabric

### Log Output

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2022-11-13 14:26:38
Description: mouseClicked event handler

java.lang.NoSuchMethodError: 'net.minecraft.class_4185$class_7840 net.minecraft.class_4185.method_46430(net.minecraft.class_2561, net.minecraft.class_4185$class_4241)'
	at me.shedaniel.clothconfig2.gui.entries.BooleanListEntry.<init>(BooleanListEntry.java:70)
	at me.shedaniel.clothconfig2.impl.builders.BooleanToggleBuilder$1.<init>(BooleanToggleBuilder.java:101)
	at me.shedaniel.clothconfig2.impl.builders.BooleanToggleBuilder.build(BooleanToggleBuilder.java:101)
	at me.cominixo.betterf3.config.gui.modules.EditModulesScreen.configBuilder(EditModulesScreen.java:61)
	at me.cominixo.betterf3.config.gui.modules.ModulesScreen.lambda$init$0(ModulesScreen.java:68)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.shedaniel.clothconfig2.gui.entries.BooleanListEntry.<init>(BooleanListEntry.java:70)
	at me.shedaniel.clothconfig2.impl.builders.BooleanToggleBuilder$1.<init>(BooleanToggleBuilder.java:101)
	at me.shedaniel.clothconfig2.impl.builders.BooleanToggleBuilder.build(BooleanToggleBuilder.java:101)
	at me.cominixo.betterf3.config.gui.modules.EditModulesScreen.configBuilder(EditModulesScreen.java:61)
	at me.cominixo.betterf3.config.gui.modules.ModulesScreen.lambda$init$0(ModulesScreen.java:68)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)

-- Affected screen --
Details:
	Screen name: me.cominixo.betterf3.config.gui.modules.ModulesScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['TimmiPlayz'/263, l='ClientLevel', x=455.00, y=67.00, z=-100.29]]
	Chunk stats: 4096, 1261
	Level dimension: minecraft:overworld
	Level spawn location: World: (368,68,-16), Section: (at 0,4,0 in 23,4,-1; chunk contains blocks 368,-64,-16 to 383,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 3401862 game time, 4636803 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fullbright 1.19 - optifine.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 983933632 bytes (938 MiB) / 3791650816 bytes (3616 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2486
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2225
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 19394.01
	Virtual memory used (MB): 13750.38
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 91.63
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betterf3: BetterF3 4.0.0
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v9 9.0.92
		fabric-api: Fabric API 0.66.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.1+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.3+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.0+a1d87cb890
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.33+70efcffe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.20+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.7+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.10+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.18+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.0+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.13+12bfe4ea90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.15+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.16+12bfe4ea90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.3+3e1ba48e90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.0+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabricloader: Fabric Loader 0.14.10
		iris: Iris 1.4.0
			io_github_douira_glsl-transformer: glsl-transformer 1.0.0-pre21.2
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		xaerominimap: Xaero's Minimap 22.16.2
		xaeroworldmap: Xaero's World Map 1.28.3
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.10-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 522.25, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Fullbright 1.19 - optifine.zip, Fabric Mods
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['TimmiPlayz'/263, l='ServerLevel[Survival World]', x=455.00, y=67.00, z=-100.29]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
```

**Comment by TreyRuffy** [comment]
You are using the wrong version of cloth config. Downgrade to v8. Version 9 is only for 1.19.3+.
