### ISSUE TITLE
[Bug]: Game crash when pressing f3

### ISSUE THREAD

**Issue by MqcCheeze** [cominixo/BetterF3#124]
### Describe the Bug

https://pastebin.com/sARugNCb

Game crashes with exit code -1 when pressing f3 to bring up the modded f3 menu

java.lang.NoClassDefFoundError: net/minecraft/class_7924.......

### Steps to Reproduce

Simply pressing F3 in-game

### Expected Behavior

The BetterF3 menu to appear

### Modloader Type

Fabric

### Modloader Version

Quilted Fabric 0.17.6

### Mod Version

BetterF3 v4.0.0

### Log Output

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 2022-11-30 00:41:17
Description: Unexpected error

java.lang.NoClassDefFoundError: net/minecraft/class_7924
	at me.cominixo.betterf3.modules.LocationModule.update(LocationModule.java:88)
	at net.minecraft.class_340.newLeftText(class_340.java:4241)
	at net.minecraft.class_340.handler$dca001$renderLeftText(class_340.java:4419)
	at net.minecraft.class_340.method_1847(class_340.java)
	at net.minecraft.class_340.method_1846(class_340.java:123)
	at net.minecraft.class_329.method_1753(class_329.java:275)
	at net.minecraft.class_757.method_3192(class_757.java:862)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_7924
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.cominixo.betterf3.modules.LocationModule.update(LocationModule.java:88)
	at net.minecraft.class_340.newLeftText(class_340.java:4241)
	at net.minecraft.class_340.handler$dca001$renderLeftText(class_340.java:4419)
	at net.minecraft.class_340.method_1847(class_340.java)
	at net.minecraft.class_340.method_1846(class_340.java:123)
	at net.minecraft.class_329.method_1753(class_329.java:275)

-- Affected level --
Details:
	All players: 1 total; [class_746['MqcCheeze'/3, l='ClientLevel', x=348.17, y=83.00, z=231.72]]
	Chunk stats: 16384, 3255
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,83,0), Section: (at 0,3,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2683050 game time, 6000 day time
	Server brand: quilt
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Vanilla Tweaks 1.19, Lower Fire, 3D Doors, continuity/glass_pane_culling_fix, continuity/default, armorchroma/alternative-icons

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3112173568 bytes (2968 MiB) / 4676648960 bytes (4460 MiB) up to 7516192768 bytes (7168 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2187
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6231
	Graphics card #1 name: LuminonCore IDDCX Adapter
	Graphics card #1 vendor: LuminonCore
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=1.0.2018.1204
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28925.22
	Virtual memory used (MB): 20296.86
	Swap memory total (MB): 12800.00
	Swap memory used (MB): 501.12
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7G
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		| Index | Mod                                               | ID                                            | Version                      |
		|------:|---------------------------------------------------|-----------------------------------------------|------------------------------|
		|    74 | Architectury                                      | architectury                                  | 6.3.56                       |
		|    26 | Armor Chroma                                      | armorchroma                                   | 1.2.3                        |
		|    68 | Better Biome Blend                                | betterbiomeblend                              | 1.19-1.3.6-fabric            |
		|    23 | Better Mount HUD                                  | bettermounthud                                | 1.2.0                        |
		|   127 | BetterF3                                          | betterf3                                      | 5.0.0                        |
		|     7 | CaffeineConfig                                    | caffeineconfig                                | 1.0.0+1.17                   |
		|     6 | Carpet Extra                                      | carpet-extra                                  | 1.4.84                       |
		|   106 | Carpet Mod                                        | carpet                                        | 1.4.84                       |
		|    76 | Cloth Config v8                                   | cloth-config                                  | 8.2.88                       |
		|    25 | Continuity                                        | continuity                                    | 2.0.1+1.19                   |
		|    36 | Controlling For Fabric                            | controlling                                   | 10.0+7                       |
		|    16 | Dynamic FPS                                       | dynamicfps                                    | 2.2.0                        |
		|    21 | EntityCulling-Fabric                              | entityculling                                 | 1.5.2-mc1.19                 |
		|    60 | Error Notifier                                    | error_notifier                                | 1.0.9                        |
		|    94 | Falling Leaves                                    | fallingleaves                                 | 1.13.0+1.19.2                |
		|   123 | FerriteCore                                       | ferritecore                                   | 5.0.3                        |
		|    24 | Indium                                            | indium                                        | 1.0.9+mc1.19.2               |
		|    41 | Iris                                              | iris                                          | 1.4.3                        |
		|    32 | Java HotSpot(TM) 64-Bit Server VM                 | java                                          | 17                           |
		|   124 | Kirin UI                                          | kirin                                         | 1.11.1                       |
		|    11 | Krypton                                           | krypton                                       | 0.2.1                        |
		|    15 | LazyDFU                                           | lazydfu                                       | 0.1.3                        |
		|    66 | LibZoomer                                         | libzoomer                                     | 0.5.0+1.19                   |
		|     4 | Litematica                                        | litematica                                    | 0.12.5                       |
		|     9 | MaLiLib                                           | malilib                                       | 0.13.0                       |
		|   111 | Minecraft                                         | minecraft                                     | 1.19.2                       |
		|     5 | MiniHUD                                           | minihud                                       | 0.23.3                       |
		|     0 | MixinExtras                                       | com_github_llamalad7_mixinextras              | 0.0.11                       |
		|    52 | Mod Menu                                          | modmenu                                       | 4.1.1                        |
		|    49 | Ok Zoomer                                         | ok_zoomer                                     | 5.0.0-beta.9+1.19            |
		|   132 | Presence Footsteps                                | presencefootsteps                             | 1.6.3                        |
		|   130 | Quilt Advancement API                             | quilt_advancement                             | 3.0.0-beta.22+1.19.2         |
		|    61 | Quilt Base API                                    | quilt_base                                    | 3.0.0-beta.22+1.19.2         |
		|    80 | Quilt Biome API                                   | quilt_biome                                   | 3.0.0-beta.22+1.19.2         |
		|   126 | Quilt Block Content Registry API                  | quilt_block_content_registry                  | 3.0.0-beta.22+1.19.2         |
		|    53 | Quilt Block Entity API                            | quilt_block_entity                            | 3.0.0-beta.22+1.19.2         |
		|    39 | Quilt Block Extensions API                        | quilt_block_extensions                        | 3.0.0-beta.22+1.19.2         |
		|    79 | Quilt Client Command API                          | quilt_client_command                          | 3.0.0-beta.22+1.19.2         |
		|    37 | Quilt Command API                                 | quilt_command                                 | 3.0.0-beta.22+1.19.2         |
		|    77 | Quilt Crash Info                                  | quilt_crash_info                              | 3.0.0-beta.22+1.19.2         |
		|    67 | Quilt DataFixerUpper API                          | quilt_datafixerupper                          | 3.0.0-beta.22+1.19.2         |
		|    46 | Quilt Dimension API                               | quilt_dimension                               | 3.0.0-beta.22+1.19.2         |
		|    62 | Quilt Entity API                                  | quilt_entity                                  | 3.0.0-beta.22+1.19.2         |
		|   112 | Quilt Entity Events                               | quilt_entity_events                           | 3.0.0-beta.22+1.19.2         |
		|    48 | Quilt Entity Networking API                       | quilt_entity_networking                       | 3.0.0-beta.22+1.19.2         |
		|    29 | Quilt Item Content Registry API                   | quilt_item_content_registry                   | 3.0.0-beta.22+1.19.2         |
		|    65 | Quilt Item Extension API                          | quilt_item_extension                          | 3.0.0-beta.22+1.19.2         |
		|    86 | Quilt Item Group API                              | quilt_item_group                              | 3.0.0-beta.22+1.19.2         |
		|    27 | Quilt Item Setting API                            | quilt_item_setting                            | 3.0.0-beta.22+1.19.2         |
		|   114 | Quilt Lifecycle Events                            | quilt_lifecycle_events                        | 3.0.0-beta.22+1.19.2         |
		|    81 | Quilt Loader                                      | quilt_loader                                  | 0.17.6                       |
		|    34 | Quilt Multipart Entity API                        | quilt_entity_multipart                        | 3.0.0-beta.22+1.19.2         |
		|    96 | Quilt Networking                                  | quilt_networking                              | 3.0.0-beta.22+1.19.2         |
		|    63 | Quilt Points of Interest                          | quilt_points_of_interest                      | 3.0.0-beta.22+1.19.2         |
		|   102 | Quilt Recipe API                                  | quilt_recipe                                  | 3.0.0-beta.22+1.19.2         |
		|    88 | Quilt Registry API                                | quilt_registry                                | 3.0.0-beta.22+1.19.2         |
		|    75 | Quilt Registry Entry Attachment                   | quilt_registry_entry_attachment               | 3.0.0-beta.22+1.19.2         |
		|    91 | Quilt Resource Loader                             | quilt_resource_loader                         | 3.0.0-beta.22+1.19.2         |
		|    89 | Quilt Screen API                                  | quilt_screen                                  | 3.0.0-beta.22+1.19.2         |
		|   116 | Quilt Status Effect API                           | quilt_status_effect                           | 3.0.0-beta.22+1.19.2         |
		|   108 | Quilt Surface Rule API                            | quilt_surface_rule                            | 3.0.0-beta.22+1.19.2         |
		|    92 | Quilt Tags API                                    | quilt_tags                                    | 3.0.0-beta.22+1.19.2         |
		|   109 | Quilt Tooltip API                                 | quilt_tooltip                                 | 3.0.0-beta.22+1.19.2         |
		|    51 | Quilt Vehicle API                                 | quilt_vehicle                                 | 3.0.0-beta.22+1.19.2         |
		|    56 | Quilt Villager API                                | quilt_villager                                | 3.0.0-beta.22+1.19.2         |
		|    97 | Quilted Fabric API                                | quilted_fabric_api                            | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    73 | Quilted Fabric API Base                           | quilted_fabric_api_base                       | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    84 | Quilted Fabric API Lookup API (v1)                | quilted_fabric_api_lookup_api_v1              | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    70 | Quilted Fabric Biome API (v1)                     | quilted_fabric_biome_api_v1                   | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   117 | Quilted Fabric Block API (v1)                     | quilted_fabric_block_api_v1                   | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   129 | Quilted Fabric BlockRenderLayer Registration (v1) | quilted_fabric_blockrenderlayer_v1            | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   125 | Quilted Fabric Client Tags                        | quilted_fabric_client_tags_api_v1             | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    45 | Quilted Fabric Command API (v1)                   | quilted_fabric_command_api_v1                 | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    47 | Quilted Fabric Command API (v2)                   | quilted_fabric_command_api_v2                 | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    43 | Quilted Fabric Commands (v0)                      | quilted_fabric_commands_v0                    | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    59 | Quilted Fabric Containers (v0)                    | quilted_fabric_containers_v0                  | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   120 | Quilted Fabric Content Registries (v0)            | quilted_fabric_content_registries_v0          | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    58 | Quilted Fabric Convention Tags API (v1)           | quilted_fabric_convention_tags_api_v1         | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    35 | Quilted Fabric Crash Report Info (v1)             | quilted_fabric_crash_report_info_v1           | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    78 | Quilted Fabric Data Generation API (v1)           | quilted_fabric_data_generation_api_v1         | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    98 | Quilted Fabric Dimensions API (v1)                | quilted_fabric_dimensions_v1                  | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    57 | Quilted Fabric Entity Events (v1)                 | quilted_fabric_entity_events_v1               | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   107 | Quilted Fabric Events Interaction (v0)            | quilted_fabric_events_interaction_v0          | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    72 | Quilted Fabric Events Lifecycle (v0)              | quilted_fabric_events_lifecycle_v0            | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    38 | Quilted Fabric Game Rule API (v1)                 | quilted_fabric_game_rule_api_v1               | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    64 | Quilted Fabric Item API (v1)                      | quilted_fabric_item_api_v1                    | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    30 | Quilted Fabric Item Groups (v0)                   | quilted_fabric_item_groups_v0                 | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   131 | Quilted Fabric Key Binding API (v1)               | quilted_fabric_key_binding_api_v1             | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   113 | Quilted Fabric Key Bindings (v0)                  | quilted_fabric_keybindings_v0                 | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    82 | Quilted Fabric Lifecycle Events (v1)              | quilted_fabric_lifecycle_events_v1            | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   105 | Quilted Fabric Loot API (v2)                      | quilted_fabric_loot_api_v2                    | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    28 | Quilted Fabric Loot Tables (v1)                   | quilted_fabric_loot_tables_v1                 | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    71 | Quilted Fabric Message API (v1)                   | quilted_fabric_message_api_v1                 | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   122 | Quilted Fabric Mining Level API (v1)              | quilted_fabric_mining_level_api_v1            | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    69 | Quilted Fabric Models (v0)                        | quilted_fabric_models_v0                      | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    40 | Quilted Fabric Networking (v0)                    | quilted_fabric_networking_v0                  | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    33 | Quilted Fabric Networking API (v1)                | quilted_fabric_networking_api_v1              | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    55 | Quilted Fabric Object Builder API (v1)            | quilted_fabric_object_builder_api_v1          | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   121 | Quilted Fabric Particles (v1)                     | quilted_fabric_particles_v1                   | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   110 | Quilted Fabric Registry Sync (v0)                 | quilted_fabric_registry_sync_v0               | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    83 | Quilted Fabric Renderer - Indigo                  | quilted_fabric_renderer_indigo                | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    31 | Quilted Fabric Renderer API (v1)                  | quilted_fabric_renderer_api_v1                | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    42 | Quilted Fabric Renderer Registries (v1)           | quilted_fabric_renderer_registries_v1         | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    90 | Quilted Fabric Rendering (v0)                     | quilted_fabric_rendering_v0                   | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    93 | Quilted Fabric Rendering (v1)                     | quilted_fabric_rendering_v1                   | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    50 | Quilted Fabric Rendering Data Attachment (v1)     | quilted_fabric_rendering_data_attachment_v1   | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    87 | Quilted Fabric Rendering Fluids (v1)              | quilted_fabric_rendering_fluids_v1            | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    44 | Quilted Fabric Resource Conditions API (v1)       | quilted_fabric_resource_conditions_api_v1     | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   115 | Quilted Fabric Resource Loader (v0)               | quilted_fabric_resource_loader_v0             | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   118 | Quilted Fabric Screen API (v1)                    | quilted_fabric_screen_api_v1                  | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    99 | Quilted Fabric Screen Handler API (v1)            | quilted_fabric_screen_handler_api_v1          | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   101 | Quilted Fabric Sound API (v1)                     | quilted_fabric_sound_api_v1                   | 4.0.0-beta.22+0.67.1-1.19.2  |
		|   104 | Quilted Fabric Textures (v0)                      | quilted_fabric_textures_v0                    | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    95 | Quilted Fabric Transfer API (v1)                  | quilted_fabric_transfer_api_v1                | 4.0.0-beta.22+0.67.1-1.19.2  |
		|    85 | Quilted Fabric Transitive Access Wideners (v1)    | quilted_fabric_transitive_access_wideners_v1  | 4.0.0-beta.22+0.67.1-1.19.2  |
		|     8 | Reese's Sodium Options                            | reeses-sodium-options                         | 1.4.7+mc1.19.2-build.59      |
		|    20 | Roughly Enough Items                              | roughlyenoughitems                            | 9.1.574                      |
		|    18 | Smooth Boot                                       | smoothboot                                    | 1.19-1.7.1                   |
		|   128 | Smooth Swapping                                   | smoothswapping                                | 0.6                          |
		|   103 | Sodium                                            | sodium                                        | 0.4.4+build.18               |
		|    54 | Sodium Extra                                      | sodium-extra                                  | 0.4.13+mc1.19.2-build.76     |
		|   119 | SpruceUI                                          | spruceui                                      | 4.0.0+1.19                   |
		|   100 | Starlight                                         | starlight                                     | 1.1.1+fabric.ae22326         |
		|     2 | Tweakeroo                                         | tweakeroo                                     | 0.14.3                       |
		|    10 | WorldEdit                                         | worldedit                                     | 7.2.12+6240-87f4ae1          |
		|    13 | antlr4-runtime                                    | org_antlr_antlr4-runtime                      | 4.10.1                       |
		|    17 | cloth-basic-math                                  | cloth-basic-math                              | 0.6.1                        |
		|    22 | glsl-transformer                                  | io_github_douira_glsl-transformer             | 1.0.1                        |
		|    14 | jcpp                                              | org_anarres_jcpp                              | 1.4.14                       |
		|     1 | joml                                              | org_joml_joml                                 | 1.10.4                       |
		|    19 | occlusionculling                                  | com_logisticscraft_occlusionculling           | 0.0.6-SNAPSHOT               |
		|     3 | toml4j                                            | com_moandjiezana_toml_toml4j                  | 0.7.2                        |
		|    12 | velocity-native                                   | com_velocitypowered_velocity-native           | 3.1.2-SNAPSHOT               |
		|------:|---------------------------------------------------|-----------------------------------------------|------------------------------|
		
	Launched Version: quilt-loader-0.17.6-1.19.2
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: GeForce GTX 1650 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 462.31, NVIDIA Corporation
	Window size: 1680x1050
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'; Server brand changed to 'quilt'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Vanilla Tweaks 1.19, file/Lower Fire, file/3D Doors, continuity/glass_pane_culling_fix, continuity/default, armorchroma/alternative-icons
	Current Language: English (United Kingdom)
	CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['MqcCheeze'/3, l='ServerLevel[RAF Base Island]', x=348.17, y=83.00, z=231.72]]
	Data Packs: vanilla
	World Generation: Stable
```

**Comment by TreyRuffy** [comment]
You are using version 5.0.0 which is only for 1.19.3. You must switch to 4.0.0.
