### ISSUE TITLE
[Bug]: Conflict with TRansliterationLib

### ISSUE THREAD

**Issue by Redls07** [cominixo/BetterF3#131]
### Describe the Bug

Forge 1.16.5 Optifine. If you try to load the game with BetterF3, Cloth config and Transliterionlib, and then go to settings of BetterF3 (F3 + M), and try to edit the modules, then visual bugs will appear, such as flickering shadows, as well as non-closing flickering borders of settings (see screenshot). Or also, from time to time, when trying to open the F3 menu, a crash may occur. If you try to run the game without an optifine, then when you try to edit the modules, there will always be a crash.

### Steps to Reproduce

Run the game with BetterF3, Cloth config and Transliterionlib, and then try to edit the modules in the mod.

### Expected Behavior

So that bugs and crashes do not manifest themselves

### Screenshots

![2023-01-14_20 36 00](https://user-images.githubusercontent.com/88981481/212474592-2c2128d7-09f2-4fa9-8c4b-a89f47371d0c.png)
![2023-01-14_20 36 06](https://user-images.githubusercontent.com/88981481/212474602-eed93d69-7c97-4ebc-8a04-f0af13e5dc27.png)
![2023-01-14_20 36 20](https://user-images.githubusercontent.com/88981481/212474612-5e08856c-12a5-4d06-8a57-1c884b2bfd5e.png)

### Modloader Type

Minecraft Forge

### Modloader Version

36.2.39

### Mod Version

1.5.0

### Log Output

```shell
---- Minecraft Crash Report ----
// Don't do that.

Time: 14.01.2023, 19:55
Description: Rendering screen

java.lang.NoSuchMethodError: 'void me.shedaniel.math.Rectangle.<init>(double, double, double, double)'
	at me.shedaniel.clothconfig2.api.AbstractConfigListEntry.render(AbstractConfigListEntry.java:75) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.entries.TooltipListEntry.render(TooltipListEntry.java:57) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.entries.BooleanListEntry.render(BooleanListEntry.java:97) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.renderItem(DynamicEntryListWidget.java:463) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderItem(ClothConfigScreen.java:394) ~[cloth-config:?] {re:classloading}
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderItem(ClothConfigScreen.java:367) ~[cloth-config:?] {re:classloading}
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.renderList(DynamicEntryListWidget.java:457) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderList(ClothConfigScreen.java:407) ~[cloth-config:?] {re:classloading}
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.func_230430_a_(DynamicEntryListWidget.java:218) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.widget.DynamicSmoothScrollingEntryListWidget.func_230430_a_(DynamicSmoothScrollingEntryListWidget.java:128) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.func_230430_a_(ClothConfigScreen.java:264) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:363) ~[forge:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:356) ~[forge:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[Forge%201.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.shedaniel.clothconfig2.api.AbstractConfigListEntry.render(AbstractConfigListEntry.java:75) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.entries.TooltipListEntry.render(TooltipListEntry.java:57) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.entries.BooleanListEntry.render(BooleanListEntry.java:97) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.renderItem(DynamicEntryListWidget.java:463) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderItem(ClothConfigScreen.java:394) ~[cloth-config:?] {re:classloading}
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderItem(ClothConfigScreen.java:367) ~[cloth-config:?] {re:classloading}
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.renderList(DynamicEntryListWidget.java:457) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderList(ClothConfigScreen.java:407) ~[cloth-config:?] {re:classloading}
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.func_230430_a_(DynamicEntryListWidget.java:218) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.widget.DynamicSmoothScrollingEntryListWidget.func_230430_a_(DynamicSmoothScrollingEntryListWidget.java:128) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.func_230430_a_(ClothConfigScreen.java:264) ~[cloth-config:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:363) ~[forge:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:356) ~[forge:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: me.shedaniel.clothconfig2.gui.ClothConfigScreen
	Mouse location: Scaled: (308, 253). Absolute: (925.000000, 759.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Redls'/123, l='ClientLevel', x=-1248.89, y=69.00, z=4744.80]]
	Chunk stats: Client Chunk Cache: 1369, 654
	Level dimension: minecraft:overworld
	Level spawn location: World: (32,66,16), Chunk: (at 0,4,0 in 2,1; contains blocks 32,0,16 to 47,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10320 game time, 10320 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:458) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterf3.mixins.json:autof3.AutomaticDebugMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[Forge%201.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1404674616 bytes (1339 MB) / 2147483648 bytes (2048 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 14 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms2048M -Xmx4096M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		BetterF3-1.5.0-Forge-1.16.5.jar                   |BetterF3                      |betterf3                      |1.5.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		transliterationlib-1.0.4.jar                      |TRansliterationLib Mod        |transliterationlib            |1.0.4               |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.16.91-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.16.91             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f62e6cfc-6fc8-4ea0-8aff-212b1d75e364
	Launched Version: Forge 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 522.25, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: Русский (Россия)
	CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
```

### Additional Context

This bug is typical only for the mod version 1.5.0. On 1.1.3 such a bug is not observed.
The crash log was generated after a crash when trying to edit modules when starting the game without optifine.

**Comment by Redls07** [comment]
Not relevant, as BetterF3 no longer receive updates for 1.16.5 and TRansliterationLib is no longer required for the latest versions of Minecraft
