### ISSUE TITLE
[Bug]: Crash When trying to edit the config in any way.

### ISSUE THREAD

**Issue by djmrFunnyMan** [cominixo/BetterF3#135]
### Describe the Bug

If I enter mod setting, no matter if through modmenu or F3 + M.  always crash with java.lang.NoSuchMethodError.

### Steps to Reproduce

It happens whenever I do absolutely anything in the settings menu. Below are the other mods I have installed and a bunch of the crashlogs.

[crash-2023-03-08_17.13.56-client.txt](https://github.com/cominixo/BetterF3/files/10922755/crash-2023-03-08_17.13.56-client.txt)
[crash-2023-03-08_17.16.21-client.txt](https://github.com/cominixo/BetterF3/files/10922756/crash-2023-03-08_17.16.21-client.txt)
[crash-2023-03-08_17.17.52-client.txt](https://github.com/cominixo/BetterF3/files/10922757/crash-2023-03-08_17.17.52-client.txt)
[crash-2023-03-08_17.19.44-client.txt](https://github.com/cominixo/BetterF3/files/10922758/crash-2023-03-08_17.19.44-client.txt)
[crash-2023-03-08_17.28.12-client.txt](https://github.com/cominixo/BetterF3/files/10922759/crash-2023-03-08_17.28.12-client.txt)
[crash-2023-03-08_17.13.01-client.txt](https://github.com/cominixo/BetterF3/files/10922760/crash-2023-03-08_17.13.01-client.txt)
[mods.zip](https://github.com/cominixo/BetterF3/files/10922764/mods.zip)

### Expected Behavior

The game wouldn't crash

### Modloader Type

Fabric

### Modloader Version

0.14.14-1.19.2

### Mod Version

4.0.0

### Log Output

```shell
17:28:12.647
net.minecraft.class_310
Render thread
Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:494)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:315)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_4185$class_7840 net.minecraft.class_4185.method_46430(net.minecraft.class_2561, net.minecraft.class_4185$class_4241)'
	at me.shedaniel.clothconfig2.gui.entries.BooleanListEntry.<init>(BooleanListEntry.java:70)
	at me.shedaniel.clothconfig2.impl.builders.BooleanToggleBuilder$1.<init>(BooleanToggleBuilder.java:101)
	at me.shedaniel.clothconfig2.impl.builders.BooleanToggleBuilder.build(BooleanToggleBuilder.java:101)
	at me.cominixo.betterf3.config.gui.GeneralOptionsScreen.configBuilder(GeneralOptionsScreen.java:42)
	at me.cominixo.betterf3.config.gui.ModConfigScreen.lambda$init$2(ModConfigScreen.java:37)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	... 16 more
17:28:13.338
monitor
Process Monitor
Process crashed with exit code -1
```

**Comment by TreyRuffy** [comment]
You are using the wrong Cloth Config version. Use v8 for 1.19.2
