### ISSUE TITLE
[Bug]:1.19.2 IndexOutOfBoundsException

### ISSUE THREAD

**Issue by CKY-** [cominixo/BetterF3#152]
### Describe the Bug

java.lang.IndexOutOfBoundsException: Index 10 out of bounds for length 10
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at me.cominixo.betterf3.modules.EntityModule.update(EntityModule.java:82) ~[BetterF3-4.0.0-Forge-1.19.2.jar%23594!/:?]
	at net.minecraft.client.gui.components.DebugScreenOverlay.newLeftText(DebugScreenOverlay.java:667) ~[client-1.19.2-20220805.130853-srg.jar%23961!/:?]
	at net.minecraft.client.gui.components.DebugScreenOverlay.handler$bnb000$renderLeftText(DebugScreenOverlay.java:845) ~[client-1.19.2-20220805.130853-srg.jar%23961!/:?]
	at net.minecraft.client.gui.components.DebugScreenOverlay.m_94076_(DebugScreenOverlay.java) ~[client-1.19.2-20220805.130853-srg.jar%23961!/:?]
	at net.minecraft.client.gui.components.DebugScreenOverlay.m_94056_(DebugScreenOverlay.java:120) ~[client-1.19.2-20220805.130853-srg.jar%23961!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.handler$bni000$customDebugMenu(ForgeGui.java:756) ~[forge-1.19.2-43.2.14-universal.jar%23966!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.renderHUDText(ForgeGui.java:459) ~[forge-1.19.2-43.2.14-universal.jar%23966!/:?]
	at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$17(VanillaGuiOverlay.java:153) ~[forge-1.19.2-43.2.14-universal.jar%23966!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:141) ~[forge-1.19.2-43.2.14-universal.jar%23966!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23121!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_93030_(ForgeGui.java:136) ~[forge-1.19.2-43.2.14-universal.jar%23966!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:876) ~[client-1.19.2-20220805.130853-srg.jar%23961!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23961!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23961!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23961!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23961!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.14.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
	
	i have a 4gig file filled with this error 

### Steps to Reproduce

load the game open the menu and look at an entity 

### Expected Behavior

not to error on invalid index

### Modloader Type

Minecraft Forge

### Modloader Version

1.19.2 43.2.14

### Mod Version

4.0.0

**Comment by XRealismX** [comment]
Also have the same problem but index and length says 11.

**Comment by X-XLebyshek** [comment]
> Also have the same problem but index and length says 11.

Yes me too, also 11
