### ISSUE TITLE
Crash while teleporting long distances with Bukkit plugin

### ISSUE THREAD

**Issue by Eiim** [cominixo/BetterF3#36]
I got this crash while teleporting a few thousand blocks using the /home command from the [Essentials](https://dev.bukkit.org/projects/essentials) Bukkit plugin with BetterF3 open. Shorter distances don't crash.

First few lines of stacktrace:
```
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "this.value" is null
	at me.cominixo.betterf3.utils.DebugLine.toText(DebugLine.java:51) ~[BetterF3-1.1.3+1.17-pre1.jar:?]
	at me.cominixo.betterf3.modules.BaseModule.getLinesFormatted(BaseModule.java:93) ~[BetterF3-1.1.3+1.17-pre1.jar:?]
	at net.minecraft.class_340.getNewLeftText(class_340.java:2182) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_340.handler$bch000$renderLeftText(class_340.java:2260) ~[intermediary-minecraft-1.17.1-client.jar:?]
```

**Comment by Eiim** [comment]
This also happens while going through a nether portal.

**Comment by cominixo** [comment]
Thanks for the report, I'll look into it as soon as I can

**Comment by cominixo** [comment]
Also, it would help to get a full crash report if that's possible

**Comment by TreyRuffy** [comment]
Closing unless there is a crash report to suggest the issue still exists.
