### ISSUE TITLE
[Bug]: F3 Crashing Minecraft with Optifine

### ISSUE THREAD

**Issue by haloTT100** [cominixo/BetterF3#53]
### Describe the Bug

Pressing down F3 instantly crashes Minecraft.

### Steps to Reproduce

Load into a world -> Press F3 -> Crash

### Expected Behavior

Show the nice F3 menu.

### Modloader Type

Minecraft Forge

### Modloader Version

38.0.14

### Mod Version

1.2.1

### Log Output

```shell
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/5/21, 3:08 AM
Description: Unexpected error

org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for me.cominixo.betterf3.mixin.chunk.WorldRendererAccessor. Mixin is defined in betterf3.mixins.json and cannot be referenced directly
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.0.7.jar:9.0.7+91+master.8569cdf] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.0.7.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.0.7.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.7.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.54.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at me.cominixo.betterf3.modules.GraphicsModule.update(GraphicsModule.java:41) ~[BetterF3-1.2.1-Forge-1.18.jar%2352!:?] {re:classloading}
	at net.minecraft.client.gui.components.DebugScreenOverlay.newLeftText(DebugScreenOverlay.java:935) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:betterf3.mixins.json:DebugMixin,pl:mixin:A}
	at net.minecraft.client.gui.components.DebugScreenOverlay.handler$zza000$renderLeftText(DebugScreenOverlay.java:1110) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:betterf3.mixins.json:DebugMixin,pl:mixin:A}
	at net.minecraft.client.gui.components.DebugScreenOverlay.m_94076_(DebugScreenOverlay.java) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:betterf3.mixins.json:DebugMixin,pl:mixin:A}
	at net.minecraft.client.gui.components.DebugScreenOverlay.m_94056_(DebugScreenOverlay.java:137) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:betterf3.mixins.json:DebugMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.handler$zzc000$customDebugMenu(ForgeIngameGui.java:974) ~[forge-1.18-38.0.14-universal.jar%2358!:?] {re:mixin,re:classloading,pl:mixin:APP:betterf3.forge.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:679) ~[forge-1.18-38.0.14-universal.jar%2358!:?] {re:mixin,re:classloading,pl:mixin:APP:betterf3.forge.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.lambda$static$17(ForgeIngameGui.java:270) ~[forge-1.18-38.0.14-universal.jar%2358!:?] {re:mixin,re:classloading,pl:mixin:APP:betterf3.forge.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.lambda$render$26(ForgeIngameGui.java:363) ~[forge-1.18-38.0.14-universal.jar%2358!:?] {re:mixin,re:classloading,pl:mixin:APP:betterf3.forge.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.m_93030_(ForgeIngameGui.java:357) ~[forge-1.18-38.0.14-universal.jar%2358!:?] {re:mixin,re:classloading,pl:mixin:APP:betterf3.forge.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1216) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18-38.0.14.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.0.7.jar:9.0.7+91+master.8569cdf] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.0.7.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.0.7.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.7.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.54.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at me.cominixo.betterf3.modules.GraphicsModule.update(GraphicsModule.java:41) ~[BetterF3-1.2.1-Forge-1.18.jar%2352!:?] {re:classloading}
	at net.minecraft.client.gui.components.DebugScreenOverlay.newLeftText(DebugScreenOverlay.java:935) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:betterf3.mixins.json:DebugMixin,pl:mixin:A}
	at net.minecraft.client.gui.components.DebugScreenOverlay.handler$zza000$renderLeftText(DebugScreenOverlay.java:1110) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:betterf3.mixins.json:DebugMixin,pl:mixin:A}
	at net.minecraft.client.gui.components.DebugScreenOverlay.m_94076_(DebugScreenOverlay.java) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:betterf3.mixins.json:DebugMixin,pl:mixin:A}
	at net.minecraft.client.gui.components.DebugScreenOverlay.m_94056_(DebugScreenOverlay.java:137) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:betterf3.mixins.json:DebugMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.handler$zzc000$customDebugMenu(ForgeIngameGui.java:974) ~[forge-1.18-38.0.14-universal.jar%2358!:?] {re:mixin,re:classloading,pl:mixin:APP:betterf3.forge.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:679) ~[forge-1.18-38.0.14-universal.jar%2358!:?] {re:mixin,re:classloading,pl:mixin:APP:betterf3.forge.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.lambda$static$17(ForgeIngameGui.java:270) ~[forge-1.18-38.0.14-universal.jar%2358!:?] {re:mixin,re:classloading,pl:mixin:APP:betterf3.forge.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.lambda$render$26(ForgeIngameGui.java:363) ~[forge-1.18-38.0.14-universal.jar%2358!:?] {re:mixin,re:classloading,pl:mixin:APP:betterf3.forge.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.m_93030_(ForgeIngameGui.java:357) ~[forge-1.18-38.0.14-universal.jar%2358!:?] {re:mixin,re:classloading,pl:mixin:APP:betterf3.forge.mixins.json:ForgeIngameGuiMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['haloTT100'/134, l='ClientLevel', x=-128.35, y=64.00, z=-56.51]]
	Chunk stats: 961, 560
	Level dimension: minecraft:overworld
	Level spawn location: World: (17,63,15), Section: (at 1,15,15 in 1,3,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 19909 game time, 4656 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:517) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2249) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:682) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18-20211130.085255-srg.jar%2354!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18-38.0.14.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default, Soartex_Fanver_(8.0.2).zip

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2492669400 bytes (2377 MiB) / 4764729344 bytes (4544 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e98
	Graphics card #1 versionInfo: DriverVersion=27.20.100.9466
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 49054.54
	Virtual memory used (MB): 22878.41
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 690.86
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ConcGCThreads=1 -XX:ParallelGCThreads=6 -Xmx8192M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Launched Version: 1.18-forge-38.0.14
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Soartex_Fanver_(8.0.2).zip (incompatible)
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['haloTT100'/134, l='ServerLevel[New World]', x=-128.34, y=64.00, z=-56.51]]
	Data Packs: vanilla, mod:cloth_config (incompatible), mod:forge, mod:betterf3
	OptiFine Version: OptiFine_1.18_HD_U_H3_pre7
	OptiFine Build: 20211204-201715
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 472.12
	OpenGlRenderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18-20211130.085255-srg.jar               |Minecraft                     |minecraft                     |1.18                |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		BetterF3-1.2.1-Forge-1.18.jar                     |BetterF3                      |betterf3                      |1.2.1               |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.0.45-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.0.45              |DONE      |Manifest: NOSIGNATURE
		forge-1.18-38.0.14-universal.jar                  |Forge                         |forge                         |38.0.14             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
	Crash Report UUID: 6f901544-fdda-4635-b83e-d60e56484984
	FML: 38.0
	Forge: net.minecraftforge:38.0.14
```

### Additional Context

Using OptiFine 1.18 HD U H3 pre7

**Comment by TreyRuffy** [comment]
I have been able to reproduce this but have not yet found a fix to it.

**Comment by haloTT100** [comment]
So, I was curios to see if the mod crashes with the Iris Shaders mod, and it doesn't crash WITH a loaded shader. When I tried with Optifine the shader wasn't even loaded in. So, it's a good workaround for now.
![Screenshot_4](https://user-images.githubusercontent.com/44986488/144747256-a17ed564-b20c-4d00-a2af-8b9faa133d85.png)

**Comment by TreyRuffy** [comment]
Looking into it, Optifine just made a change in their 1.18 release for LevelRenderer and now the accessor (WorldRendererAccessor) no longer works. I am still not sure about how to fix it but I will ask around. It might take a couple of days.

**Comment by TreyRuffy** [comment]
Good news, I just found a fix and will upload it to CurseForge and Modrinth very soon!

**Comment by Pedrozaquieu** [comment]
very soon... :(

**Comment by TreyRuffy** [comment]
> very soon... :(

I believe this was already fixed. Are you still experiencing the issue on the latest version?

**Comment by DREYTOR98** [comment]
is not fixet yet
