### ISSUE TITLE
[Bug]: 1.18.1 not supported! **Crash**

### ISSUE THREAD

**Issue by Wesley51** [cominixo/BetterF3#56]
### Describe the Bug

When launching on 1.18.1, the client crashes with an error shown below:

### Steps to Reproduce

Launch the server with 1.18.1 Fabric

### Expected Behavior

The client should startup.

### Modloader Type

Fabric

### Modloader Version

0.12.12

### Mod Version

1.1.5

### Log Output

```shell
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'BetterF3' (betterf3) 1.1.5 (C:\Users\hoywe\AppData\Roaming\.minecraft\mods\betterf3-1.1.5+1.17.jar) with any version that is compatible with:
		 - minecraft 1.18.1
Unmet dependency listing:
	 - Mod 'BetterF3' (betterf3) 1.1.5 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
		 - 'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - mod 'BetterF3' (betterf3) 1.1.5, reason: to replace
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: inactive parent mod (nested jar)
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.33, reason: inactive parent mod (nested jar)
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.7+b7ab6121d5, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'MidnightLib' (midnightlib) 0.2.9, reason: newer version active
	 - mod 'lambdajcommon' (org_aperlambda_lambdajcommon) 1.8.1, reason: same version active
	 - mod 'SpruceUI' (spruceui) 3.3.0+1.17, reason: same version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'BetterF3' (betterf3) 1.1.5 (C:\Users\hoywe\AppData\Roaming\.minecraft\mods\betterf3-1.1.5+1.17.jar) with any version that is compatible with:
		 - minecraft 1.18.1
Unmet dependency listing:
	 - Mod 'BetterF3' (betterf3) 1.1.5 requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.1!
		 - 'Minecraft' (minecraft) 1.18.1 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - mod 'BetterF3' (betterf3) 1.1.5, reason: to replace
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: inactive parent mod (nested jar)
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.33, reason: inactive parent mod (nested jar)
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.7+b7ab6121d5, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'MidnightLib' (midnightlib) 0.2.9, reason: newer version active
	 - mod 'lambdajcommon' (org_aperlambda_lambdajcommon) 1.8.1, reason: same version active
	 - mod 'SpruceUI' (spruceui) 3.3.0+1.17, reason: same version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more
```

**Comment by cominixo** [comment]
Update to 1.2.2.

**Comment by Wesley51** [comment]
`net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:122)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:122)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:204)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing C:\Users\hoywe\AppData\Roaming\.minecraft\mods\BetterF3-1.2.2-Fabric-1.18.jar: java.util.zip.ZipException: zip file is empty
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:119)
	... 5 more
Caused by: java.lang.RuntimeException: Error analyzing C:\Users\hoywe\AppData\Roaming\.minecraft\mods\BetterF3-1.2.2-Fabric-1.18.jar: java.util.zip.ZipException: zip file is empty
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:218)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:175)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1598)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1382)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:237)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:213)
	... 7 more
`

**Comment by Wesley51** [comment]
I feel so stupid that I just opened this bug report and THAT was the issue. Pardon my stupidiness!
