### ISSUE TITLE
[Bug]: Crash when pressing F3

### ISSUE THREAD

**Issue by Molarczsq** [cominixo/BetterF3#74]
### Describe the Bug

Game Crash

### Steps to Reproduce

touch F3 in game

### Expected Behavior

Game crash

### Modloader Type

Fabric

### Modloader Version

0.14.4

### Mod Version

1.2.4

### Log Output

```shell
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/2/22, 5:25 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "s" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at me.cominixo.betterf3.modules.MiscLeftModule.update(MiscLeftModule.java:58)
	at net.minecraft.client.gui.hud.DebugHud.newLeftText(DebugHud:2226)
	at net.minecraft.client.gui.hud.DebugHud.handler$bhb000$renderLeftText(DebugHud:2403)
	at net.minecraft.client.gui.hud.DebugHud.renderLeftText(DebugHud)
	at net.minecraft.client.gui.hud.DebugHud.render(DebugHud:117)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:297)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:858)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.cominixo.betterf3.modules.MiscLeftModule.update(MiscLeftModule.java:58)
	at net.minecraft.class_340.newLeftText(class_340.java:2226)
	at net.minecraft.class_340.handler$bhb000$renderLeftText(class_340.java:2403)
	at net.minecraft.class_340.method_1847(class_340.java)
	at net.minecraft.class_340.method_1846(class_340.java:117)
	at net.minecraft.class_329.method_1753(class_329.java:297)

-- Affected level --
Details:
	All players: 1 total; [class_746['Molarczsq'/247, l='ClientLevel', x=25.04, y=87.00, z=-8.71]]
	Chunk stats: 1024, 621
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,81,0), Section: (at 0,1,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 886 game time, 886 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, charmonium/journeyman, minecraft/supporteatinganimation, fabric-diagonal-panes/default, KubeJS Resource Pack [assets]

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1932077432 bytes (1842 MiB) / 8162115584 bytes (7784 MiB) up to 8162115584 bytes (7784 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f95
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1259
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=27.20.100.9664
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26783.31
	Virtual memory used (MB): 24392.37
	Swap memory total (MB): 10531.52
	Swap memory used (MB): 1396.14
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx7782m
	Fabric Mods: 
		additionaladditions: Additional Additions 4.0.0
		additionalbars: Additional Bars 3.0.0
		additionalstructures: Additional Structures 3.0.3
		adorn: Adorn 3.4.0+1.18.2
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
		airhop: Air Hop 3.2.0
		alloy_forgery: Alloy Forgery 2.0.13+1.18
		alloygery: Alloygery 2-rc+3
		amplified-nether: Amplified Nether 1.1
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.2
		animatica: Animatica 0.4+1.18
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.2.50
		artifacts: Artifacts 7.0.3+fabric
		attributefix: AttributeFix 14.0.1
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 3.0.0+0
		bclib: BCLib 1.4.5
		bedrockify: BedrockIfy 1.4.1+mc1.18.2
		beenfo: Beenfo 1.18.2-fabric0.47.10-1.3.3
		better-snowball-fight: Better Snowball Fight 0.1
		betteradvancements: Better Advancements 0.2.0.129
		betterbeds: Better Beds 1.2.0
		betterbiomeblend: Better Biome Blend 1.18.2-1.3.4-fabric
		betterend: Better End 1.1.0
		betterf3: BetterF3 1.2.3
		betterfpsdist: Better FPS distance Mod 1.18-1.8
		bettermounthud: Better Mount HUD 1.1.4
		betternether: Better Nether 6.1.1
		bettertaskbar: Better Taskbar 1.3
		bewitchment: Bewitchment 1.18-18
		birdsnests: Bird's Nests 1.0.0+1.18.2
		bitsandchisels: BitsAndChisels 2.6.8
		blockus: Blockus 2.4.5+1.18.2
		blue_endless_jankson: jankson 1.2.1
		bno: Basic Nether Ores 1.18.2-7.2.0-Fabric
		bookshelf: Bookshelf 13.0.13
		breakprogress: Break Progress 1.0.1
		bwplus: Bewitchment Plus 1.18.2-16
		byg: Oh The Biomes You'll Go 1.4
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.7.0
		cacao: Croptopia's Chocolaterie 1.1
		caffeineconfig: CaffeineConfig 1.1.0
		campanion: Campanion 3.0.3
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.2.0
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		carrier: Carrier 1.10.0
		cauldron_dyeing: Cauldron Dyeing 1.0.2+1.18.2
		cem: Custom Entity Models 0.7.1
		chalk: Chalk 2.0.0+1.18.2
		charm: Charm 4.1.0
		charmonium: Charmonium 4.0.0
		chestcavity: Chest Cavity 2.16.2
		chesttracker: Chest Tracker 1.1.13
		chime: Chime 1.2.1
		cleancut: CleanCut 1.18-4.0-fabric
		clienttweaks: Client Tweaks 7.1.0
		cloth-api: Cloth API 3.2.64
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.2.64
		cloth-common-events-v1: Cloth Common Events v1 3.2.64
		cloth-config: Cloth Config v6 6.2.57
		cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
		cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
		cloth-utils-v1: Cloth Utils v1 3.2.64
		collective-fabric: Collective (Fabric) 4.26
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_llamalad7_mixinextras: mixinextras 0.0.8
		com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
		com_google_code_findbugs_jsr305: jsr305 3.0.2
		com_ishland_c2me_libs_: libs 0.2.0+alpha.7.0
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 1.1.2-1.18.2
		companion: Companion 2.0.1
		completeconfig: CompleteConfig 1.0.0
		continuity: Continuity 1.1.0+1.18.2
		cooldown-coordinator: Cooldown Coordinator 0.3.0
		craftingtweaks: Crafting Tweaks 13.0.0
		create: Create mc1.18.2_v0.4.1+530
		creativecore: CreativeCore (Fabric) 2.6.10
		creatures_of_the_jungle: Creatures From The Jungle 1.0.0
		creeperoverhaul: Creeper Overhaul 1.3.0
		crimsonmoon: Crimson Moon 2.2.1-1.18.2
		crops_love_rain: Crops Love Rain 1.2.2
		croptopia: Croptopia 2.0.0
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		culinaire: Culinaire 2.4.0
		cullleaves: Cull Leaves 2.3.2
		customportalapi: Custom Portal Api 0.0.1-beta50-1.18
		customskinloader: CustomSkinLoader 14.13
		customsplashscreen: Custom Splash Screen 1.2.0
		darkpaintings: DarkPaintings 10.0.1
		dawn: Dawn API 3.3.0
		dbm: Dispenser Bazooka Mod 1.0.6
		debugify: Debugify 1.9.0
		decorative_blocks: Decorative Blocks 2.1.0
		decorative_winter: Decorative Winter 2.1.0
		detailab: Detail Armor Bar 2.6.2+1.18-fabric
		dimension_data_fix: Dimension Data Fix 1.0.1
		doubledoors-fabric: Double Doors (Fabric) 3.3
		draggable-resource-packs: Draggable Resource Packs 2.0.0
		drinkbeer: Drink Beer 3.0.2
		drinkit: Drink It 1.18.2-1.0.0
		dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
		dsurround: §6Dynamic Surroundings§r: §eFabric Edition 0.0.4
		dual_riders: DualRiders 1.0.5
		dualwielding: Dual Wielding 1.0.8
		duckling: Duckling 1.0.4
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dynamicfps: Dynamic FPS 2.1.0
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.18.2
		easiervillagertrading: EasierVillagerTrading 1.18.2-fabric0.47.10-1.5.4
		eatinganimationid: Eating Animation 1.6
		ebb: Elytra Bombing 1.18.X-1.0.0
		ecologics: Ecologics 1.5.4
		effective: Effective 1.2.1
		emerald_tools: Emerald Tools 1.3.43
		enchantinginfuser: Enchanting Infuser 3.2.0
		enchantment_force: enchantment_force 0.1.7
		enchdesc: EnchantmentDescriptions 10.0.3
		endsky: Custom End Sky 1.3
		enhancedblockentities: Enhanced Block Entities 0.6+1.18.2
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.4
		entityculling: EntityCulling-Fabric 1.5.1
		expandability: ExpandAbility 6.0.0
		expandedstorage: Expanded Storage 7.3.12
		extensibleenums: Extensible Enums 3.0.0
		fabric: Fabric API 0.51.1+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 2.0.7+6d3e563660
		fabric-diagonal-panes: Fabric Diagonal Panes 0.6.1
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.3+2d83e92c60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabrication: Fabrication 2.3.1-exp3
		fabricloader: Fabric Loader 0.14.4
		fake-player-api: Fake Player API 0.3.0
		fallingleaves: Falling Leaves 1.10.0+1.18.2
		farmingforblockheads: Farming for Blockheads 10.0.0
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		fiber: fiber 0.23.0-2
		fishontheline-fabric: Fish On The Line (Fabric) 1.2
		fluidtank: Fluid Tank 18.5.0-fabric
		flywheel: Flywheel 1.18-0.6.2.25
		forge_tags: Forge Tags 2.1
		forgeconfigapiport: Forge Config API Port 3.2.0
		forgivingvoid: Forgiving Void 6.0.1
		friendsandfoes: Friends&Foes 1.3.4
		gateofbabylon: Gate Of Babylon 1.7.0-1.18.2
		gbfabrictools: GBfabrictools 1.3.4+1.18.2
		geckolib3: Geckolib 3.0.38
		glassdoor: Glass Doors 2.1.0+1.18
		goblintraders: Goblin Traders 1.5.1
		goprone: GoProne unknown
		gravelminer: GravelMiner 12.0.0
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.12
		gud_recipe_confidence: Recipe Confidence 1.0.2
		guild: Guild 0.4.0
		hardcorerevival: Hardcore Revival 8.0.0
		healingcampfire-fabric: Healing Campfire (Fabric) 3.3
		healingsoup-fabric: Healing Soup (Fabric) 2.4
		hellfire: Hellfire:Fireball Launcher 1.0.1
		iceberg: Iceberg 1.0.38
		iknowwhatimdoing: I Know What I'm Doing 4.0.0
		illagerexp: Illager Expansion 0.1.5
		illuminations: Illuminations 1.10.3
		imblocker: IMBlockerFabric 1.0.18
		immersive_weathering: Immersive Weathering 2.4.0
		impersonate: Impersonate 2.4.1
		incendium: Incendium + Seed Fix 5.0.3
		incubus_core: Incubus Core 1.6.6+1.18.2
		indium: Indium 1.0.3+mc1.18.2
		interactic: Interactic 0.1.10+1.18
		inventoryhud: Inventory HUD + 3.4.2
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.2.4-build.38
		jankson: Jankson 4.0.0+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		justenoughkeys: Just Enough Keys 0.5.3
		kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		kiwi: Kiwi Lib 6.0.2
		kleeslabs: KleeSlabs 11.0.0
		krypton: Krypton 0.1.9
		kubejs: KubeJS 1802.5.1-build.372
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazy-language-loader: lazy-language-loader 0.3.0
		lazydfu: LazyDFU 0.1.2
		leaf-decay: Leaf Decay 1.4.0-1.18.1
		libblockattributes: LibBlockAttributes 0.10.2
		libblockattributes_core: LibBlockAttributes (Core) 0.10.2
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.2
		libblockattributes_items: LibBlockAttributes (Items) 0.10.2
		libgui: LibGui 5.3.1+1.18
		libninepatch: LibNinePatch 1.1.0
		lightoverlay: Light Overlay 6.0.5
		lithium: Lithium 0.7.9
		llamasteeds: Llama Steeds 2020.2.8
		lucky: Lucky Block 1.18.2-13.0
		magna: Magna 1.7.0-1.18-pre1
		maybe-data: Maybe data 1.2.1-1.18.2
		mcda: MC Dungeons Armors 2.0.6
		mcdar: MC Dungeons Artifacts 1.4.7
		mcdw: MC Dungeons Weapons 4.3.2
		mcwifipnp: LAN World Plug-n-Play 1.5.4
		midnightlib: MidnightLib 0.4.0
		milk: Milk Lib 0.3.1
		milk_plus: Milk+ 3.0.1
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		modern_industrialization: Modern Industrialization 1.1.1
		modid: Creatures Of The Snow 1.0.0
		modify-drops-api: Modify Drops API 0.4.0.2
		modmenu: Mod Menu 3.2.1
		morebannerfeatures: More Banner Features 1.1.3
		moreleads: Moreleads 1.18.2-1.0.0
		moretags: More Tags 3.0.3
		morevillagers-fabric: MoreVillagersFabric 3.2.0-SNAPSHOT
		mostructures: Mo' Structures 1.4.1+1.18.2
		mousetweaks: Mouse Tweaks 2.22
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		nbtcrafting: NBT Crafting 2.1.3+mc1.18.2
		netherportalfix: NetherPortalFix 9.0.0
		nextspring: NextSpring 1.18.2-1.0.0
		nimble: Nimble 2.2.1
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.3.0
		nohostilesaroundcampfire-fabric: No Hostiles Around Campfire (Fabric) 3.8
		noindium: No Indium? 1.0.1+1.18.2
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		omega-config: OmegaConfig 1.2.3-1.18.1
		omnihopper: Omni-Hopper 1.1.1
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_commons_commons-compress: commons-compress 1.19
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		org_tukaani_xz: xz 1.9
		owo: oωo 0.7.0+1.18
		paintings: Paintings++ 9.1.1.0
		particlerain: Particle Rain 2.0.0
		patchouli: Patchouli 1.18.2-67-FABRIC
		paxi: Paxi 1.18.2-Fabric-2.0
		pehkui: Pehkui 3.3.0+1.14.4-1.19
		pistorder: Pistorder 1.5.0
		playerabilitylib: Pal 1.5.0
		polymorph: Polymorph 0.0.20-1.18.2
		porting_lib: Porting Lib 0.2.0+1.18.2.2e6c4b3
		pride: Pride Lib 1.1.0+1.17
		publicguiannouncement: Public Gui Announcement 3.2.0.1
		puddles: Puddles 1.2.1
		pugh_tools: Pugh Tools 1.2.5
		puzzleslib: Puzzles Lib 3.3.1
		quickplant: QuickPlant 1.18.2-1.0.0
		rare-ice: Rare Ice 0.4.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		registrate-fabric: Registrate for Fabric MC1.18.2-1.0.x
		regrowth: Regrowth 0.28b.release
		replantingcrops-fabric: Replanting Crops (Fabric) 2.5
		repurposed_structures: Repurposed Structures 4.1.6+1.18.2
		resolutioncontrol: ResolutionControl+ 3.0.0+1.18
		rhino: Rhino 1801.1.9-build.135
		roughlyenoughitems: Roughly Enough Items 8.1.457
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		sandwichable: Sandwichable 1.2+1.18.2
		satin: Satin 1.7.2
		secondchance: Second Chance 1.3.0
		seedfix: Seed Fix 1.0.1
		server-hats: Server Hats 0.9
		sextant: Immersive Travel Overhaul 1.2
		shelve: Shelve Refabricated 0.0.3-1.18.2
		sit: Sit 1.18.2-18
		skinlayers: 3d Skin Layers 1.4.4-mc1.18.2
		smoothboot: Smooth Boot 1.18.2-1.7.0
		smwyg: Show Me What You Got 1.0.1
		sneakycurses: Sneaky Curses 3.0.0
		snowrealmagic: Snow! Real Magic! 4.0.0
		sodium: Sodium 0.4.1+build.15
		sodium-extra: Sodium Extra 0.4.3
		splash_milk: Splash Milk 1.0.2
		spruceui: SpruceUI 3.3.0+1.17
		spyglass-improvements: Spyglass Improvements 1.2+mc1.18.2+fabric
		spyzoom: Spyglass Zoom 1.0.2
		sspb: Sodium Shadowy Path Blocks 0.2.3
		stacc: Stacc 1.2.3
		starlight: Starlight 1.0.2+fabric.89b8d9f
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.4.3
		team_reborn_energy: Energy 2.2.0
		terrablender: TerraBlender 1.1.0.99
		terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		textile_backup: Textile Backup 2.3.0-1.18
		the_aether: Paradise Lost 1.6.8+1.18.2
		the_bumblezone: The Bumblezone - Fabric 5.0.10+1.18.2
		thonkutil: ThonkUtil 2.12.0+1.18
		thonkutil-base: ThonkUtil Base 1.12.0+93f5607360
		thonkutil-capes-v1: ThonkUtil Capes (v1) 1.3.1+974d16dd60
		thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.18+4c66479160
		thonkutil-customization-v1: ThonkUtil Customization (v1) 1.0.13+4c66479160
		thonkutil-legacy: ThonkUtil Legacy 1.0.19+aa74e18060
		thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.0.11+4c66479160
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.4.0+6d0d59d760
		thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.1.8+4c66479160
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.19+4c66479160
		thorium: thorium 1.1.1
		tinyskeletons: Tiny Skeletons 3.2.1
		totw_additions: Towers of the Wild: Additions 1.2.1
		tradingpost: Trading Post 3.2.0
		transportables: Transportables 1.1
		trinkets: Trinkets 3.3.0
		universalbonemeal: Universal Bone Meal 3.0.4
		universalenchants: Universal Enchants 3.0.6
		villagerquests: Villager Quests 1.0.3
		visualworkbench: Visual Workbench 3.3.0
		waveycapes: WaveyCapes 1.2.0
		waystones: Waystones 10.0.0
		weaponmaster: YDM's Weapon Master 1-18-x
		whereisit: Where Is It 1.14.10
		wolveswitharmor: Wolves With Armor 1.7.1-1.18.2
		woodarmor: Wooden Armors (+ Stone Armor) fabric-1.18.2-v1.0.1
		wooltweaks-fabric: Wool Tweaks (Fabric) 1.5
		world-data: World Data 1.0.3-1.18.2
		wthit: wthit 4.9.1
		xaerominimap: Xaero's Minimap 22.6.1
		xaeroworldmap: Xaero's World Map 1.20.7
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.7
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.18.2-Fabric 0.14.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.59, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.' x 1
id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Size and/or offset out of range.' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.' x 1
id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Size and/or offset out of range.' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.' x 1
id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Size and/or offset out of range.' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.' x 1
id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Size and/or offset out of range.' x 1
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.' x 1
id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Size and/or offset out of range.' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods, charmonium/journeyman, minecraft/supporteatinganimation
	Current Language: 简体中文 (中国)
	CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Molarczsq'/247, l='ServerLevel[新的世界]', x=25.04, y=87.00, z=-8.71]]
	Data Packs: vanilla, minecraft/croptop, Fabric Mods
	World Generation: Stable
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader)
```

**Comment by TreyRuffy** [comment]
This should be fixed in 1.2.5.
