### ISSUE TITLE
[Bug]: Conflict with presencefootsteps

### ISSUE THREAD

**Issue by SettingDust** [cominixo/BetterF3#86]
### Describe the Bug

Can't shou debug info
https://github.com/Sollace/Presence-Footsteps/issues/149

### Steps to Reproduce

presencefootsteps

### Expected Behavior

show debug

### Modloader Type

Minecraft Forge

### Modloader Version

40.1.48

### Mod Version

1.2.5

### Log Output

```shell
[21:42:42] [Render thread/ERROR] (ForgeIngameGui) Error rendering overlay 'Text Columns'
java.lang.NullPointerException: Cannot invoke "eu.ha3.presencefootsteps.PFDebugHud.render(net.minecraft.world.phys.HitResult, net.minecraft.world.phys.HitResult, java.util.List)" because the return value of "eu.ha3.presencefootsteps.PresenceFootsteps.getDebugHud()" is null
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.components.DebugScreenOverlay.handler$bll000$onGetRightText(DebugScreenOverlay.java:2096)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.components.DebugScreenOverlay.m_94078_(DebugScreenOverlay.java:405)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.components.DebugScreenOverlay.newRightText(DebugScreenOverlay.java:682)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.components.DebugScreenOverlay.handler$zdc000$renderRightText(DebugScreenOverlay.java:709)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.components.DebugScreenOverlay.m_94079_(DebugScreenOverlay.java)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.gui.components.DebugScreenOverlay.m_94056_(DebugScreenOverlay.java:116)
	at TRANSFORMER/forge@40.1.48/net.minecraftforge.client.gui.ForgeIngameGui.handler$zde000$customDebugMenu(ForgeIngameGui.java:963)
	at TRANSFORMER/forge@40.1.48/net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:664)
	at TRANSFORMER/forge@40.1.48/net.minecraftforge.client.gui.ForgeIngameGui.lambda$static$17(ForgeIngameGui.java:255)
	at TRANSFORMER/forge@40.1.48/net.minecraftforge.client.gui.ForgeIngameGui.lambda$render$26(ForgeIngameGui.java:348)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at TRANSFORMER/forge@40.1.48/net.minecraftforge.client.gui.ForgeIngameGui.m_93030_(ForgeIngameGui.java:342)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:870)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.48/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
```
```


### Additional Context

_No response_

**Comment by TreyRuffy** [comment]
This is a problem with the forge port of Presence Footsteps. This has nothing to do with BetterF3. The issue has already been reported PaintNinja/Presence-Footsteps-Forge#2 and PaintNinja/Presence-Footsteps-Forge#3.
