### ISSUE TITLE
[Bug]: Crash on Pressing F3

### ISSUE THREAD

**Issue by SirInfinite** [cominixo/BetterF3#87]
### Describe the Bug

A game crash that happens when you press the button F3 on your keyboard.

### Steps to Reproduce

<details open>
<summary>Mod List:</summary>
Note: The number in parentheses is the mod version (as in Version 1.0, 2.0), and NOT the Minecraft version (as in 1.18.2, 1.19). <br />
- 3D Skin Layers (1.4.7) <br />
- Advanced Compass (1.2.7) <br />
- AppleSkin (2.4.0) <br />
- Architectury API (5.6.21) <br />
- BetterF3 (1.3.0) <br />
- BetterMountHUD (1.1.4) <br />
- BetterTaskbar (1.4) <br />
- C2ME (0.2.0) <br />
- Carpet (1.4.79) <br />
- Clear Skies (2.0.93) <br />
- Client Side Noteblocks (2.2) <br />
- Cloth Config (7.0.69)<br />
- Clumps (9.0.0)<br />
- Continuity (2.0.0) <br />
- Controlling (10.0) <br />
- Cull Leaves (2.3.4) <br />
- DetailArmorBar (2.6.2) <br />
- DynamicFPS (2.1.0) <br />
- Effective (1.2.2) <br />
- EntityCulling (1.5.2) <br />
- FabricAPI (0.55.3) <br />
- Ferritecore (5.0.0) <br />
- Figura (0.0.8) <br />
- Illuminations (1.10.5) <br />
- Indium (1.0.4) <br />
- InventoryHUD+ (3.4.5) <br />
- Krypton (0.2.0) <br />
- LazyDFU (0.1.3) <br />
- ModMenu (4.0.0) <br />
- Pistorder (1.5.0) <br />
- Plasmovoice (1.2.14) <br />
- Rainbowify (2.0.0) <br />
- Reeses Sodium Options (1.4.3) <br />
- Resclone <br />
- RoughlyEnoughItems (9.0.472) <br />
- RoughlyEnoughProfessions (1.0.1) <br />
- RoughlySearchable (2.5.0) <br />
- Shield Indicator (1.0.1 <br />
- Show Me Your Skin (1.2.1) <br />
- Sodium Extra (0.4.5) <br />
- Sodium (0.4.2) <br />
- Sodium Shadowy Path Blocks (2.0.0) <br />
- Starlight (1.1.0) <br />
- Suggestion Tweaker (1.2.1) <br />
- TieFix (1.11.0) <br />
- Tooltip Tweaks (1.1.0) <br />
- UI Input Undo (1.2.0) <br />
- Visuality (0.5.0) <br />
- WPIT (1.4.0)
</details>

Load up the launcher.
Go into any singleplayer world (**have not tested on Multiplayer**) and press F3.

### Expected Behavior

When the F3 button is pressed, the F3 menu would open, with all of my previous saved assets and setting configurations saved to it.

### Screenshots

n/A

### Modloader Type

Fabric

### Modloader Version

Version 0.55.3 (Minecraft Version 1.19)

### Mod Version

Version 1.3.0

### Log Output

```shell
---- Minecraft Crash Report ----
// Don't do that.

Time: 6/9/22, 2:09 PM
Description: Unexpected error

java.lang.NoSuchFieldError: field_1910
	at net.minecraft.class_329.handler$cdk000$injectedRender(class_329.java:8549)
	at net.minecraft.class_329.method_1736(class_329.java:475)
	at net.minecraft.class_329.method_1753(class_329.java:230)
	at net.minecraft.class_757.method_3192(class_757.java:862)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_329.handler$cdk000$injectedRender(class_329.java:8549)
	at net.minecraft.class_329.method_1736(class_329.java:475)
	at net.minecraft.class_329.method_1753(class_329.java:230)

-- Affected level --
Details:
	All players: 1 total; [class_746['SirInfinity'/66, l='ClientLevel', x=424.47, y=116.22, z=1529.94]]
	Chunk stats: 1024, 598
	Level dimension: minecraft:overworld
	Level spawn location: World: (-112,62,-48), Section: (at 0,14,0 in -7,3,-3; chunk contains blocks -112,-64,-48 to -97,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 6220 game time, 6220 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, cullleaves/smartleaves, Default-Dark-Mode-1.19-0.5-000000-(v1.3.2).zip, Essential (fabric_1.19).jar

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 422433640 bytes (402 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=27.20.1034.6
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 19394.54
	Virtual memory used (MB): 14384.00
	Swap memory total (MB): 11264.00
	Swap memory used (MB): 618.86
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancedcompass: Advanced Compass 1.2.7
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.6.21
		betterf3: BetterF3 1.3.0
		bettermounthud: Better Mount HUD 1.1.4
		bettertaskbar: Better Taskbar 1.4
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.8.0
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.8.0
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.8.0
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.8.0
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.8.0
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.8.0
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.8.0
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.8.0
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.8.0
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.8.0
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.8.0
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.8.0
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.8.0
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.8.0
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.8.0
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.8.0
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.8.0
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.8.0
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.8.0
			c2me-threading-scheduling: Concurrent Chunk Management Engine (Threading/Scheduling) 0.2.0+alpha.8.0
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.8.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			org_threadly_threadly: threadly 7.0
		carpet: Carpet Mod 1.4.79
		clear-skies: Clear Skies 2.0.93
		clientsidenoteblocks: ClientSideNoteblocks 2.2
		continuity: Continuity 2.0.0+1.19
		cullleaves: Cull Leaves 2.3.4
			midnightlib: MidnightLib 0.5.2
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		dynamicfps: Dynamic FPS 2.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		effective: Effective 1.2.2
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		essential: Essential 3018+feature-fabric-1.19
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		fabric: Fabric API 0.55.3+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.6+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.12+e62f51a3a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.5+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.1+cda9839ba9
			fabric-commands-v0: Fabric Commands (v0) 0.2.22+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.16+9ff28f40a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.0.1+2a5b9210a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.24+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.23+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.9+21a5acaaa9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.1+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.1+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.7+9ff28f40a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.5+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.16+92cf9a3ea9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.6+9ff28f40a9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+9e7660c6a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.23+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.8+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.7
		ferritecore: FerriteCore 4.2.1
		figura: Figura 0.0.8+1.19
			com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
			org_luaj_luaj-jse: luaj-jse 3.0.1
		illuminations: Illuminations 1.10.5
		indium: Indium 1.0.4+mc1.19
		inventoryhud: Inventory HUD + 3.4.2
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.0
		mousewheelie: Mouse Wheelie 1.8.9+mc1.19-pre1
			amecsapi: Amecs API 1.3.6+mc22w17a
			coat: Coat 1.0.0-beta.17+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		pistorder: Pistorder 1.5.0
		plasmo_voice: Plasmo Voice 1.2.14
		rainbowify: Rainbowify 2.0.0-alpha.1
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		resclone: Resclone 1.9.0
			libjf-base: LibJF Base 2.9.1
		roughlyenoughitems: Roughly Enough Items 9.0.472
		roughlysearchable: Roughly Searchable 2.5.0+1.19
		shield_indicator: Shield Indicator 1.0.1
		showmeyourskin: Show Me Your Skin! 1.2.1+1.19
		skinlayers: 3d Skin Layers 1.4.7-mc1.19
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sspb: Sodium Shadowy Path Blocks 2.0.0
		starlight: Starlight 1.1.0+fabric.eb9df34
		suggestion_tweaker: Suggestion Tweaker 1.19-1.2.1
		tiefix: TieFix 1.11.0
		tooltiptweaks: Tooltip Tweaks 1.1.0
			cloth-config: Cloth Config v6 7.0.69
				cloth-basic-math: cloth-basic-math 0.6.1
		uiinputundo: UI Input Undo 1.2.0
		visuality: Visuality 0.5.0
		wpit: WPIT 1.4.0
	Launched Version: fabric-loader-0.14.7-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Radeon RX 580 Series GL version 3.2.13596 Core Profile Forward-Compatible Context 20.10.35.02 27.20.1034.6, ATI Technologies Inc.
	Window size: 2560x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, cullleaves/smartleaves, file/Default-Dark-Mode-1.19-0.5-000000-(v1.3.2).zip
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['SirInfinity'/66, l='ServerLevel[New World]', x=424.47, y=116.22, z=1529.94]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
```

**Comment by TreyRuffy** [comment]
Does this happen when you just use BetterF3 and not all the rest of the mods? If it doesn't, can you try to take out some of your mods to help narrow down which mod it is. The stacktrace says there is no `reducedDebugInfo` field, so anything that might mess with that.

**Comment by SirInfinite** [comment]
ah, i just checked and you were right. i just uninstalled betterf3 and it still crashed.

the weird part was before this (earlier today), at some point the mod was working fine. i could open and close the f3 menu with ease. so it must've been a mod i put in sometime between the time it worked and now. the only couple of mods that i can think of in that time period are continuity, controlling, reeses sodium options and inventorygui+. do you know any of my mods that may be incompatible with betterf3?

also im not really sure about the reducedDebugInfo part, not many of my mods stand out as messing with that part

**Comment by TreyRuffy** [comment]
I would just remove one mod at a time until you are able to figure out which one it is and I can see if there's a fix with that mod specifically then.

**Comment by SirInfinite** [comment]
ok so here is the thing
i went through, and split the mods into sections and split them apart to see which ones are "safe" and which one would crash my computer
so essentially when i got to the last mod, and i tested it, it all worked.
all 50ish mods worked, but when i put the mods together they crash
separately i can press f3 and it'll work for every single mod, but together they crash.
at first i thought "there has got to be something incompatible", but i would suppose minecraft would give a warning if that was the case. and as far as i can tell literally none of my other mods does anything to the f3 menu.
im using fabric, but with fabric im using essential (a mod that makes compatibility with mods easier to read)
so i tried loading in fabric client alone and got a completely different error message, that had to do with feather client. but then i tried it on FEATHER client and got a *COMPLETLEY DIFFERENT ERROR MESSAGE.* currently im working with the people from feather client to get back to me, but im not really sure what to do.

**Comment by SirInfinite** [comment]
whoops accidentally closed the issue

**Comment by TreyRuffy** [comment]
In that case, there's not much I personally can do unless I can get more information. If the client crashes with BetterF3 uninstalled then it must be another mod and using trial and error to find which one is the best way to go about it.
