### ISSUE TITLE
[Crash]: with Shield Indicator mod

### ISSUE THREAD

**Issue by kirmerk1** [cominixo/BetterF3#89]
### Describe the Bug

Game crashing with Shield Indicator mod after pressing F3. I think it's happends because of gizmo/cursor conflict. But somehow everything works fine with Dynamic Crosshair mod.

### Steps to Reproduce

Just press F3 eksdee

### Expected Behavior

Crash

### Modloader Type

Fabric

### Modloader Version

0.14.7

### Mod Version

1.3.1

### Log Output

```shell
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 6/13/22, 12:39 AM
Description: Unexpected error

java.lang.NoSuchFieldError: field_1910
	at net.minecraft.class_329.handler$cha000$injectedRender(class_329.java:5049)
	at net.minecraft.class_329.method_1736(class_329.java:475)
	at net.minecraft.class_329.method_1753(class_329.java:230)
	at net.minecraft.class_757.method_3192(class_757.java:862)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_329.handler$cha000$injectedRender(class_329.java:5049)
	at net.minecraft.class_329.method_1736(class_329.java:475)
	at net.minecraft.class_329.method_1753(class_329.java:230)

-- Affected level --
Details:
	All players: 1 total; [class_746['kirmerk'/81, l='ClientLevel', x=-11.31, y=-60.00, z=-0.83]]
	Chunk stats: 1024, 612
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1874 game time, 1874 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Icons+Reimagined§8[v1.3].zip, continuity/default, continuity/glass_pane_culling_fix, loadmyresources.hiddenpack, Luminous1.3.zip, LeafDecay.zip, Enchanting-Reimagined§8-[v1].zip, EclecticTrove-noconfig-1.18.1-1.1.0.zip, CraftingTable-Reimagined§8-[v1].zip, Chests-Reimagined-Edited.zip, 3D-Noteblock-Displays-1.18-V2.2.zip, Blink.zip, FreshAnimations_FancyCraft.zip, VanillaTweaks_FancyCraft.zip, fixed-lower-shield-1-17.zip, brew_guide_darkmode.zip, Boss+Bars++1.18+Update.zip, Vanilla_Additions_Dark_GUI_FancyCraft_Edition.zip, Font.zip, Dark_GUI_for_mods.zip

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 491780096 bytes (468 MiB) / 2057306112 bytes (1962 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E3-1220 v3 @ 3.10GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Radeon RX 570 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.15021.1001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.87
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.87
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 22978.62
	Virtual memory used (MB): 12216.79
	Swap memory total (MB): 6656.00
	Swap memory used (MB): 6.73
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		betterf3: BetterF3 1.3.1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.3+9e7660c6a9
		cem: Custom Entity Models 0.7.1
		chat_heads: Chat Heads 0.6.0
		chunky: Chunky 1.2.202
		citresewn: CIT Resewn 1.1.0+1.19
			citresewn-defaults: CIT Resewn: Defaults 1.1.0+1.19
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		completeconfig: CompleteConfig 2.0.0
			coat: Coat 1.0.0-beta.17+mc22w17a
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
			completeconfig-gui-coat: completeconfig-gui-coat 2.0.0
		continuity: Continuity 2.0.0+1.19
		cull-less-leaves: Cull Less Leaves 1.0.2
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
		cullparticles: Cull Particles 2.0
		customskinloader: CustomSkinLoader 14.14-SNAPSHOT-325
		dark-loading-screen: Dark Loading Screen 1.6.11
		detailab: Detail Armor Bar 2.6.2+1.19-fabric
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		eatinganimationid: Eating Animation 1.8.1
		effective: Effective 1.2.2
		entity-view-distance: Entity View Distance 1.0.2+1.19
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			spruceui: SpruceUI 4.0.0+1.19
		entity_texture_features: Entity Texture Features 3.1.1
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		extrasounds: ExtraSounds 2.3.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			soundcategories: Sound Categories 1.2.4+1.19
		fabric: Fabric API 0.55.3+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.6+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.12+e62f51a3a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.5+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.1+cda9839ba9
			fabric-commands-v0: Fabric Commands (v0) 0.2.22+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.16+9ff28f40a9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.0.1+2a5b9210a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.27+72da3b3da9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.24+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.23+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.9+21a5acaaa9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.1+9e7660c6a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.1+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.7+9ff28f40a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.5+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.16+92cf9a3ea9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.6+9ff28f40a9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.23+9ff28f40a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.8+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.7
		fallingleaves: Falling Leaves 1.12.1+1.19
		fancymenu: FancyMenu 2.7.2
		fastload: Fast Load 1.0.5+1.19
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		forgetmechunk: Forget Me Chunk 1.0.4-1.18.X-1.19.X
		ias: In-Game Account Switcher 7.2.0
		idwtialsimmoedm: idwtialsimmoedm 0.1.1+1.19
		indium: Indium 1.0.4+mc1.19
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		konkrete: Konkrete 1.3.3
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.8.0
		loadmyresources: Load My Resources 1.0.1
		memoryleakfix: memory Leak Fix 1.19-0.4.1
		microdurability: microDurability 0.3.5+1.19
			microdurability-core: microDurability Core 0.3.5
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.0
		morechathistory: MoreChatHistory 1.1.0
		mousetweaks: Mouse Tweaks 2.22
		no-resource-pack-warnings: No Resource Pack Warnings 1.0.0
		norefreshscroll: NoRefreshScroll 1.0.0
		notenoughanimations: NotEnoughAnimations 1.6.0
		raised: Raised 1.1.1
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		shield_indicator: Shield Indicator 1.0.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.9+1.19
			mm: Manningham Mills 2.3
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sspb: Sodium Shadowy Path Blocks 3.0.0
		starlight: Starlight 1.1.0+fabric.eb9df34
		tooltipfix: ToolTip Fix 1.0.5-1.19
		universal-graves: Universal Graves 2.0.5+1.19
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-beta.4+1.19
			polymer: Polymer (Core) 0.2.0+1.19
				polymer-legacy: Polymer (Compatibility) 0.1.9+0.2.0+1.19
			server_translations_api: Server Translations API 1.4.14+1.19-rc2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
			sgui: sgui 1.1.0+1.19
		voicechat: Simple Voice Chat 1.19-2.2.45
		waveycapes: WaveyCapes 1.2.0
		wpit: WPIT 1.4.0
	Loaded Shaderpack: (off)
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Radeon RX 570 Series GL version 3.2.14800 Core Profile Forward-Compatible Context 22.4.1 30.0.15021.1001, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Icons+Reimagined§8[v1.3].zip (incompatible), continuity/default, continuity/glass_pane_culling_fix, loadmyresources.hiddenpack (incompatible), file/Luminous1.3.zip (incompatible), file/LeafDecay.zip (incompatible), file/Enchanting-Reimagined§8-[v1].zip (incompatible), file/EclecticTrove-noconfig-1.18.1-1.1.0.zip (incompatible), file/CraftingTable-Reimagined§8-[v1].zip (incompatible), file/Chests-Reimagined-Edited.zip (incompatible), file/3D-Noteblock-Displays-1.18-V2.2.zip (incompatible), file/Blink.zip (incompatible), file/FreshAnimations_FancyCraft.zip (incompatible), file/VanillaTweaks_FancyCraft.zip (incompatible), file/fixed-lower-shield-1-17.zip (incompatible), file/brew_guide_darkmode.zip (incompatible), file/Boss+Bars++1.18+Update.zip (incompatible), file/Vanilla_Additions_Dark_GUI_FancyCraft_Edition.zip (incompatible), file/Font.zip (incompatible), file/Dark_GUI_for_mods.zip (incompatible)
	Current Language: English (US)
	CPU: 4x Intel(R) Xeon(R) CPU E3-1220 v3 @ 3.10GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['kirmerk'/81, l='ServerLevel[New World]', x=-11.31, y=-60.00, z=-0.83]]
	Data Packs: vanilla, Fabric Mods, loadmyresources.hiddenpack (incompatible)
	World Generation: Stable
```

**Comment by TreyRuffy** [comment]
I can't find the mod. Can you send me a link to its GitHub repo or at least the mod page?

**Comment by kirmerk1** [comment]
Sure. https://modrinth.com/mod/shield-indicator/versions
https://github.com/Noryea/shield-indicator

**Comment by TreyRuffy** [comment]
Does the mod still not work correctly? From my testing, I can get it to work.
